# Generated by Django 5.0 on 2024-10-23 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fabricante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Ativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patrimonio', models.IntegerField(blank=True)),
                ('serial', models.CharField(blank=True, max_length=50)),
                ('defeito', models.CharField(blank=True, max_length=100)),
                ('data', models.DateField()),
                ('tempo_uso', models.CharField(max_length=100)),
                ('setor', models.CharField(max_length=100)),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ativos.fabricante')),
            ],
        ),
    ]
